/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.postgresql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bipin
 */
public class BillDetails extends javax.swing.JFrame {

    DbConnection dbConnection = new DbConnection();
    /**
     * Creates new form BillDetails
     */
    public BillDetails() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bill_details_scroll = new javax.swing.JScrollPane();
        bill_details_tbl = new javax.swing.JTable();

        setTitle("Bill Details");

        bill_details_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        bill_details_scroll.setViewportView(bill_details_tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bill_details_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bill_details_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillDetails().setVisible(true);
            }
        });
    }

   /*
    ------------------------------start-----------------------------------------
    list the product item  
    */    
    public ArrayList<CartList> billDetailList(int billid){
        ArrayList<CartList> billdetails = new ArrayList<>();
        
        String SQL = "select * from get_bill_details(?)";
        try(Connection conn = dbConnection.connect();
                PreparedStatement pstmt = conn.prepareStatement(SQL)){
                pstmt.setInt(1, billid);
            ResultSet rs = pstmt.executeQuery();
            CartList cart;
            while(rs.next()){
                cart = new CartList(rs.getString("product_name_table"), 
                        rs.getFloat("product_price_table"), 
                        rs.getInt("product_quantity"), 
                        rs.getFloat("product_total"));                
                billdetails.add(cart);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        return billdetails;             
    }
    
    /*
    map bill details in table
    */
    public void show_bill_details(int billid){
        ArrayList<CartList> list = billDetailList(billid);
        DefaultTableModel model;       
        model = (DefaultTableModel)bill_details_tbl.getModel();
        Object[] row = new Object[4];          
        list.stream().map((list1) -> {
            row[0] = list1.getProdName();            
            return list1;
        }).map((list1) -> {
            row[1] = list1.getProdPrice();
            return list1;
        }).map((list1) -> {
            row[2] = list1.getQuantity();
            return list1;
        }).map((list1) -> {
            row[3] = list1.getTotal();
            return list1;
        }).forEach((_item) -> {                        
            model.addRow(row);
        });
    }
    /*
    ----------------------------------end---------------------------------------
    */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bill_details_scroll;
    private javax.swing.JTable bill_details_tbl;
    // End of variables declaration//GEN-END:variables

    
}
